version: '3.4'

services:
  node:
    image: 'carcel/skeleton/dev:node'
    environment:
      API_BASE_URL: 'http://0.0.0.0:${FAKE_API_PORT:-8000}'
      CLIENT_PORT: '${CLIENT_PORT:-8080}'
      YARN_CACHE_FOLDER: '/home/yarn-cache'
    expose:
      - '${CLIENT_PORT:-8080}'
    networks:
      - skeleton-client
    ports:
      - '${CLIENT_PORT:-8080}:${CLIENT_PORT:-8080}'
    user: '${HOST_USER_IDS:-1000:1000}'
    volumes:
      - './:/srv/app'
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/yarn-cache'
      - '${HOST_YARN_CONFIG_FOLDER:-~/.yarn}:/.yarn'
      - '${HOST_YARN_CONFIG_FILE:-~/.yarnrc}:/.yarnrc'
    working_dir: '/srv/app'

  client:
    image: 'carcel/skeleton/client:latest'
    labels:
      - 'traefik.http.middlewares.redirect-skeleton-client-http-to-https.redirectScheme.scheme=https'
      - 'traefik.http.routers.skeleton-client.entrypoints=web'
      - 'traefik.http.routers.skeleton-client.middlewares=redirect-skeleton-client-http-to-https'
      - 'traefik.http.routers.skeleton-client.rule=Host(`skeleton.docker.localhost`)'
      - 'traefik.http.routers.skeleton-client-with-https.entrypoints=websecure'
      - 'traefik.http.routers.skeleton-client-with-https.rule=Host(`skeleton.docker.localhost`)'
      - 'traefik.http.routers.skeleton-client-with-https.tls=true'
    networks:
      - proxy
      - skeleton-client

networks:
  proxy:
    external: true
  skeleton-client:
