services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Repository\InMemory\BlogPostRepository:
    App\Repository\BlogPostRepositoryInterface: '@App\Repository\InMemory\BlogPostRepository'
