FROM node:lts-alpine
MAINTAINER Damien Carcel <damien.carcel@gmail.com>

RUN apk add --no-cache \
    autoconf \
    automake \
    bash \
    g++ \
    libc6-compat \
    libjpeg-turbo-dev \
    libpng-dev \
    make \
    nasm
