dist: trusty
sudo: required

language: php

php:
    - 7.2

addons:
    apt:
        sources:
            - mysql-5.7-trusty
        packages:
            - mysql-server

env:
    - TRAVIS_NODE_VERSION='10'

git:
    depth: 10

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache

before_install:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql_upgrade -u root -proot
    - sudo service mysql restart

install:
    - mysql -uroot -proot -e 'CREATE DATABASE db_name;'
    - mysql -uroot -proot -e 'GRANT ALL PRIVILEGES ON db_name.* TO db_user@localhost IDENTIFIED BY "db_password"'
    - cd ${TRAVIS_BUILD_DIR}/front && yarn install
    - cp ${TRAVIS_BUILD_DIR}/back/.env.dist ${TRAVIS_BUILD_DIR}/back/.env
    - cd ${TRAVIS_BUILD_DIR}/back && composer update --prefer-dist --optimize-autoloader --no-interaction --no-scripts
    - cd ${TRAVIS_BUILD_DIR}/back && bin/console --env=test doctrine:schema:update --force > /dev/null

script:
    - cd ${TRAVIS_BUILD_DIR}/front && yarn lint
    - cd ${TRAVIS_BUILD_DIR}/front && yarn type-check
    - cd ${TRAVIS_BUILD_DIR}/back && vendor/bin/php-cs-fixer fix --dry-run -v --diff --config=.php_cs.php
    - cd ${TRAVIS_BUILD_DIR}/back && vendor/bin/php-cs-fixer fix --dry-run -v --diff --config=.php_cs.phpspec.php
    - cd ${TRAVIS_BUILD_DIR}/back && vendor/bin/phpspec run
    - cd ${TRAVIS_BUILD_DIR}/back && APP_ENV=acceptance vendor/bin/behat --profile=acceptance
    - cd ${TRAVIS_BUILD_DIR}/back && APP_ENV=test vendor/bin/behat --profile=integration
    - cd ${TRAVIS_BUILD_DIR}/back && APP_ENV=test vendor/bin/behat --profile=end-to-end
