api_platform:
    collection:
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: _limit
            maximum_items_per_page: 50
            page_parameter_name: _page
    exception_to_status:
        Carcel\User\Domain\Exception\UserDoesNotExist: 404
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
