services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Infrastructure\Repository\InMemory\UserRepository: ~
    App\Domain\Repository\UserRepositoryInterface: '@App\Infrastructure\Repository\InMemory\UserRepository'

    App\Infrastructure\QueryFunction\InMemory\GetUserListFromMemory: ~
    App\Domain\QueryFunction\GetUserList: '@App\Infrastructure\QueryFunction\InMemory\GetUserListFromMemory'

    App\Application\Query\GetUserListHandler: ~
