services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Infrastructure\Persistence\Doctrine\Repository\UserRepository: ~
    App\Domain\Repository\UserRepositoryInterface: '@App\Infrastructure\Persistence\Doctrine\Repository\UserRepository'

    App\Infrastructure\Persistence\Doctrine\QueryFunction\GetUserListFromDatabase: ~
    App\Domain\QueryFunction\GetUserList: '@App\Infrastructure\Persistence\Doctrine\QueryFunction\GetUserListFromDatabase'
