services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Carcel\User\Infrastructure\Persistence\InMemory\Repository\UserRepository: ~
    Carcel\User\Domain\Repository\UserRepositoryInterface: '@Carcel\User\Infrastructure\Persistence\InMemory\Repository\UserRepository'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserListFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUserList: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserListFromMemory'

    Carcel\User\Application\Query\GetUserListHandler: ~
