services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Carcel\User\Infrastructure\Persistence\Doctrine\Repository\UserRepository: ~
    Carcel\User\Domain\Repository\UserRepositoryInterface: '@Carcel\User\Infrastructure\Persistence\Doctrine\Repository\UserRepository'

    Carcel\User\Infrastructure\Persistence\Doctrine\QueryFunction\GetUserListFromDatabase: ~
    Carcel\User\Domain\QueryFunction\GetUserList: '@Carcel\User\Infrastructure\Persistence\Doctrine\QueryFunction\GetUserListFromDatabase'
