Carcel\User\Domain\Model\Write\User:
    type: entity
    table: user
    id:
        id:
            type: uuid
    fields:
        username:
            type: string
            length: 255
        firstName:
            type: text
        lastName:
            type: text
