services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Infrastructure\Repository\Doctrine\UserRepository: ~
    App\Domain\Repository\UserRepositoryInterface: '@App\Infrastructure\Repository\Doctrine\UserRepository'
