services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Repository\Doctrine\BlogPostRepository: ~
    App\Domain\Repository\BlogPostRepositoryInterface: '@App\Repository\Doctrine\BlogPostRepository'
