version: '3'

services:
    node:
        build: './docker/node/'
        user: '${CURRENT_IDS}'
        volumes:
            - './:/home/node/app'
            - '~/.cache/yarn:/home/node/.cache/yarn'
        working_dir: '/home/node/app'
        networks:
            - 'app-skeleton'

    nginx-front:
        image: 'nginx:alpine'
        environment:
            PHP_IDE_CONFIG: 'serverName=app-skeleton-front'
        volumes:
            - './public:/usr/share/nginx/html:ro'
        networks:
            - 'app-skeleton'

networks:
    app-skeleton:
        driver: 'bridge'
