resources:
    Carcel\User\Application\Command\CreateUser:
        attributes:
            messenger: true
            output: false
        collectionOperations:
            post:
                path: '/users'
                status: 202
        itemOperations: {}

    Carcel\User\Application\Query\GetUser:
        properties:
            identifier:
                identifier: true
        collectionOperations: {}
        itemOperations:
            get:
                path: '/users/{id}'
                status: 201

    Carcel\User\Application\Command\UpdateUser:
        attributes:
            messenger: true
            output: false
        properties:
            identifier:
                identifier: true
        collectionOperations: {}
        itemOperations:
            put:
                path: '/users/{id}'
                status: 202

    Carcel\User\Application\Command\DeleteUser:
        attributes:
            messenger: true
            output: false
        properties:
            identifier:
                identifier: true
        collectionOperations: {}
        itemOperations:
            delete:
                path: '/users/{id}'
                status: 202
