resources:
    Carcel\User\Application\Query\GetUserCollection:
        collectionOperations:
            get:
                path: '/users'
        itemOperations: {}
        properties:
            identifier:
                identifier: true

    Carcel\User\Application\Command\UpdateUser:
        attributes:
            messenger: true
            output: false
        collectionOperations: {}
        itemOperations:
            put:
                path: '/users/{id}'
                status: 202
        properties:
            identifier:
                identifier: true
