resources:
    Carcel\User\Application\Command\UpdateUser:
        attributes:
            messenger: true
            output: false
        collectionOperations: {}
        itemOperations:
            put:
                path: '/users/{id}'
                status: 202
        properties:
            identifier:
                identifier: true
