services:
    _defaults:
        autowire: true
        autoconfigure: true

    #- Application services overrides -#

    #Carcel\Tests\EndToEnd\Acme: ~

    #- Tests only services -#

    Carcel\Tests\Fixtures\:
        resource: '../tests/fixtures'
        tags: ['doctrine.fixture.orm']

    #- Behat contexts -#

    Carcel\Tests\EndToEnd\Context\AuthenticationContext:
        public: true

    Carcel\Tests\EndToEnd\Context\CreateUserContext:
        public: true

    Carcel\Tests\EndToEnd\Context\DeleteUserContext:
        public: true

    Carcel\Tests\EndToEnd\Context\FixtureContext:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    Carcel\Tests\EndToEnd\Context\GetUserContext:
        public: true

    Carcel\Tests\EndToEnd\Context\ListUsersContext:
        public: true

    Carcel\Tests\EndToEnd\Context\UpdateUserContext:
        public: true
