services:
    _defaults:
        autowire: true
        autoconfigure: true

    #- Application services overrides -#

    #Carcel\User\Acme: ~

    #- Tests only services -#

    Carcel\Tests\Fixtures\:
        resource: '../tests/fixtures'
        tags: ['doctrine.fixture.orm']
