services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Fixtures\:
        resource: '../tests/fixtures/*'

    App\Tests\Integration\:
        resource: '../tests/integration/*'
