services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\EndToEnd\:
        resource: '../tests/end-to-end/*'

    App\Tests\Fixtures\:
        resource: '../tests/fixtures/*'

    App\Tests\Integration\:
        resource: '../tests/integration/*'
