services:
    _defaults:
        autowire: true
        autoconfigure: true

    #- Application services overrides -#

    Carcel\User\Infrastructure\Persistence\InMemory\Repository\UserRepository: ~
    Carcel\User\Domain\Repository\UserRepositoryInterface: '@Carcel\User\Infrastructure\Persistence\InMemory\Repository\UserRepository'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserCollectionFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUserCollection: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserCollectionFromMemory'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUser: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserFromMemory'

    #- Tests only services -#

    #Carcel\Tests\Acceptance\Acme: ~

    #- Behat contexts -#

    Carcel\Tests\Acceptance\Context\AuthenticationContext:
        public: true

    Carcel\Tests\Acceptance\Context\CreateUserContext:
        public: true

    Carcel\Tests\Acceptance\Context\DeleteUserContext:
        public: true

    Carcel\Tests\Acceptance\Context\FixtureContext:
        public: true

    Carcel\Tests\Acceptance\Context\GetUserCollectionContext:
        public: true

    Carcel\Tests\Acceptance\Context\GetUserContext:
        public: true

    Carcel\Tests\Acceptance\Context\UpdateUserContext:
        public: true
