services:
    _defaults:
        autowire: true
        autoconfigure: true

    #- Application services overrides -#

    #Carcel\User\Acme: ~

    #- Tests only services -#

    #Carcel\Tests\EndToEnd\Acme: ~

    #- Behat contexts -#

    Carcel\Tests\EndToEnd\Context\AuthenticationContext:
        public: true

    Carcel\Tests\EndToEnd\Context\CreateUserContext:
        public: true

    Carcel\Tests\EndToEnd\Context\DeleteUserContext:
        public: true

    Carcel\Tests\EndToEnd\Context\FixtureContext:
        public: true

    Carcel\Tests\EndToEnd\Context\GetUserContext:
        public: true

    Carcel\Tests\EndToEnd\Context\ListUsersContext:
        public: true

    Carcel\Tests\EndToEnd\Context\UpdateUserContext:
        public: true
