services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Acceptance\:
        resource: '../tests/acceptance/*'

    App\Tests\Fixtures\:
        resource: '../tests/fixtures/*'
