services:
    _defaults:
        autowire: true
        autoconfigure: true

    #- Application services overrides -#

    Carcel\User\Infrastructure\Persistence\InMemory\Repository\UserRepository: ~
    Carcel\User\Domain\Repository\UserRepositoryInterface: '@Carcel\User\Infrastructure\Persistence\InMemory\Repository\UserRepository'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserListFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUserList: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserListFromMemory'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUser: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserFromMemory'

    #- Tests only services -#

    #Carcel\Tests\Acceptance\Acme: ~

    #- Behat contexts -#

    Carcel\Tests\Acceptance\Context\AuthenticationContext:
        public: true

    Carcel\Tests\Acceptance\Context\CreateUserContext:
        public: true
        arguments:
            - '@Carcel\User\Application\Command\CreateUserHandler'
            - '@Carcel\User\Domain\Repository\UserRepositoryInterface'

    Carcel\Tests\Acceptance\Context\FixtureContext:
        public: true
        arguments:
            - '@Carcel\User\Domain\Repository\UserRepositoryInterface'

    Carcel\Tests\Acceptance\Context\GetUserContext:
        public: true
        arguments:
            - '@Carcel\User\Application\Query\GetUserHandler'

    Carcel\Tests\Acceptance\Context\ListUsersContext:
        public: true
        arguments:
            - '@Carcel\User\Application\Query\GetUserListHandler'
