services:
    _defaults:
        autowire: true
        autoconfigure: true

    #- Application services overrides -#

    Carcel\User\Infrastructure\Persistence\InMemory\Repository\InMemoryUserRepository: ~
    Carcel\User\Domain\Repository\UserRepository: '@Carcel\User\Infrastructure\Persistence\InMemory\Repository\InMemoryUserRepository'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserCollectionFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUserCollection: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserCollectionFromMemory'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUser: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserFromMemory'

    Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserPasswordFromMemory: ~
    Carcel\User\Domain\QueryFunction\GetUserPassword: '@Carcel\User\Infrastructure\Persistence\InMemory\QueryFunction\GetUserPasswordFromMemory'

    Carcel\User\Infrastructure\Security\DummyEncodePassword: ~
    Carcel\User\Domain\Service\EncodePassword: '@Carcel\User\Infrastructure\Security\DummyEncodePassword'

    #- Tests only services -#

    #Carcel\Tests\Acceptance\Acme: ~

    #- Behat contexts -#

    Carcel\Tests\Acceptance\Context\AuthenticationContext:
        public: true

    Carcel\Tests\Acceptance\Context\CreateUserContext:
        public: true

    Carcel\Tests\Acceptance\Context\DeleteUserContext:
        public: true

    Carcel\Tests\Acceptance\Context\FixtureContext:
        public: true

    Carcel\Tests\Acceptance\Context\GetUserCollectionContext:
        public: true

    Carcel\Tests\Acceptance\Context\GetUserContext:
        public: true

    Carcel\Tests\Acceptance\Context\UpdateUserContext:
        public: true
