App\Entity\BlogPost:
    type: entity
    table: blog_post
    repositoryClass: App\Repository\BlogPostRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
