version: '3.4'

services:
  api:
    build:
      context: './'
      target: 'api-nginx'
    image: 'carcel/skeleton/api:nginx'
    depends_on:
      - 'fpm'
    labels:
      - 'traefik.http.middlewares.redirect-skeleton-api-http-to-https.redirectScheme.scheme=https'
      - 'traefik.http.routers.skeleton-api.entrypoints=web'
      - 'traefik.http.routers.skeleton-api.middlewares=redirect-skeleton-api-http-to-https'
      - 'traefik.http.routers.skeleton-api.rule=Host(`skeleton-api.docker.localhost`)'
      - 'traefik.http.routers.skeleton-api-with-https.entrypoints=websecure'
      - 'traefik.http.routers.skeleton-api-with-https.rule=Host(`skeleton-api.docker.localhost`)'
      - 'traefik.http.routers.skeleton-api-with-https.tls=true'
    networks:
      - proxy
      - skeleton-api

  fpm:
    build:
      context: './'
      target: 'api-fpm'
    command: 'php-fpm -F'
    image: 'carcel/skeleton/api:fpm'
    networks:
      - skeleton-api

  api-dev:
    build:
      context: './'
      target: 'dev'
    command: 'php -S 0.0.0.0:8000'
    image: 'carcel/skeleton/dev:php'
    environment:
      PHP_CONF_DISPLAY_ERRORS: 1
      PHP_CONF_DISPLAY_STARTUP_ERRORS: 1
      PHP_CONF_ERROR_REPORTING: 32767
      PHP_CONF_OPCACHE_VALIDATE_TIMESTAMP: 1
      PHP_CONF_ZEND_ASSERTIONS: 1
      PHP_IDE_CONFIG: 'serverName=app-skeleton-api'
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
    expose:
      - '8000'
    ports:
      - '${PHP_SKELETON_OUTPUT:-8000}:8000'
    user: '${HOST_USER_IDS:-1000:1000}'
    volumes:
      - './:/srv/app:rw'
    working_dir: '/srv/app/public'
    networks:
      - skeleton-api

  php:
    build:
      context: './'
      target: 'dev'
    image: 'carcel/skeleton/dev:php'
    environment:
      COMPOSER_CACHE_DIR: '/home/composer/.cache/composer'
      COMPOSER_HOME: '/home/composer/.config/composer'
      PHP_CONF_DISPLAY_ERRORS: 1
      PHP_CONF_DISPLAY_STARTUP_ERRORS: 1
      PHP_CONF_ERROR_REPORTING: 32767
      PHP_CONF_OPCACHE_VALIDATE_TIMESTAMP: 1
      PHP_CONF_ZEND_ASSERTIONS: 1
      PHP_IDE_CONFIG: 'serverName=app-skeleton-php'
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
    user: '${HOST_USER_IDS:-1000:1000}'
    volumes:
      - './:/srv/app:rw'
      - '${HOST_COMPOSER_CACHE_DIR:-~/.cache/composer}:/home/composer/.cache/composer'
      - '${HOST_COMPOSER_HOME:-~/.config/composer}:/home/composer/.config/composer'
    working_dir: '/srv/app'
    networks:
      - skeleton-api

  mysql:
    image: 'mysql:8'
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'app_skeleton'
      MYSQL_PASSWORD: 'app_skeleton'
      MYSQL_DATABASE: 'app_skeleton'
    ports:
      - '${MYSQL_SKELETON_PORT:-33006}:3306'
    tmpfs:
      - '/tmp'
      - '/var/lib/mysql'
    networks:
      - skeleton-api

networks:
  proxy:
    external: true
  skeleton-api:
