version: '3.4'

services:
    api:
        image: 'carcel/skeleton/api:latest'
        depends_on:
            - 'fpm'
        labels:
            - 'traefik.docker.network=proxy'
            - 'traefik.frontend.rule=Host:api.skeleton.docker.local'
            - 'traefik.enable=true'
        networks:
            - 'proxy'
            - 'skeleton-back'

    fpm:
        image: 'carcel/skeleton/fpm:7.3'
        networks:
            - 'skeleton-back'

    php:
        image: 'carcel/skeleton/php:7.3'
        environment:
            COMPOSER_CACHE_DIR: '/home/composer/.cache/composer'
            COMPOSER_HOME: '/home/composer/.config/composer'
            PHP_IDE_CONFIG: 'serverName=app-skeleton'
            XDEBUG_CONFIG: 'remote_host=172.17.0.1'
            XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
        ports:
            - '${PHP_SKELETON_OUTPUT:-8000}:8000'
        user: '${HOST_USER_IDS:-1000:1000}'
        volumes:
            - './:/srv/app'
            - '${HOST_COMPOSER_CACHE_DIR:-~/.cache/composer}:/home/composer/.cache/composer'
            - '${HOST_COMPOSER_HOME:-~/.config/composer}:/home/composer/.config/composer'
        working_dir: '/srv/app'
        networks:
            - 'skeleton-back'

    mysql:
        image: 'mysql:8'
        command: ['--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'app_skeleton'
            MYSQL_PASSWORD: 'app_skeleton'
            MYSQL_DATABASE: 'app_skeleton'
        ports:
            - '${MYSQL_SKELETON_PORT:-33006}:3306'
        tmpfs:
            - '/tmp'
            - '/var/lib/mysql'
        networks:
            - 'skeleton-back'

networks:
    proxy:
        external: true
    skeleton-back:

volumes:
    var-data:
